import { create } from 'zustand'

export type Language = 'en' | 'az' | 'ru'

interface LanguageStore {
  language: Language
  setLanguage: (lang: Language) => void
  translations: Record<Language, Record<string, string>>
}

const translations = {
  en: {
    create: 'Create',
    dashboard: 'Dashboard',
    templates: 'Templates',
    credits: 'Credits',
    upgrade: 'Upgrade',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    jobs: 'My Jobs',
    billing: 'Billing',
    documents: 'Documents',
    legalDocuments: 'Legal & documents',
    privacyPolicy: 'Privacy policy',
    termsOfUse: 'Terms of use',
    cookiePolicy: 'Cookie policy',
    refundPolicy: 'Refund & cancellation policy',
    packages: 'Packages',
    landing: 'Landing',
    quickLinks: 'Quick Links',
    language: 'Language',
    english: 'English',
    azerbaijani: 'Azerbaijani',
    russian: 'Russian',
    theme: 'Theme',
    notifications: 'Notifications',
    account: 'Account',
    getStarted: 'Get Started',
    browseTemplates: 'Browse Templates',
    createAmazingContent: 'Create Amazing Content with AI',
    accessPowerfulTools: 'Access powerful AI tools for video, image, and audio generation in one unified platform',
    videoTools: 'Video Tools',
    imageTools: 'Image Tools',
    audioTools: 'Audio Tools',
    generateVideos: 'Generate, enhance, and transform videos with AI',
    createImages: 'Create stunning images from text prompts',
    generateAudio: 'Generate and process audio content with AI',
    aiToolsDashboard: 'AI Tools Dashboard',
    accessTools: 'Access powerful AI tools for video, image, and audio generation',
    availableCredits: 'Available Credits',
    lowCredits: 'Low Credits - Buy More',
    allTools: 'All Tools',
    video: 'Video',
    image: 'Image',
    audio: 'Audio',
    noToolsAvailable: 'No tools available in this category',
    selectLanguage: 'Select your desired language',
    enableNotifications: 'Enable notifications',
    receiveSystemNotifications: 'Receive system notifications',
    emailNotifications: 'Email notifications',
    receiveEmailNotifications: 'Receive notifications via email',
    darkMode: 'Dark mode',
    darkTheme: 'Dark theme',
    lightMode: 'Light mode',
    lightTheme: 'Light theme',
    changePassword: 'Change password',
    changeEmail: 'Change email address',
    payment: 'Payment',
    managePaymentMethods: 'Manage payment methods',
    accountInvoice: 'Account invoice',
    // Create page
    createPromptPlaceholder: 'What do you want to create?',
    enterPrompt: 'Please enter a prompt',
    loginRequired: 'Please login first',
    selectTool: 'Please select a tool',
    insufficientCredits: 'Insufficient credits',
    videoGenerated: 'Video generated successfully!',
    videoProcessing: 'Video is being processed. Check back soon!',
    videoGenerationFailed: 'Video generation failed. Please try again.',
    generatedVideo: 'Generated Video',
    generatingVideo: 'Generating video... This may take a few moments.',
    controls: 'Controls',
    tools: 'Tools',
    projects: 'Projects',
    firstProject: 'First project',
    noCreationsYet: 'No creations yet',
    incognito: 'Incognito',
    cost: 'Cost',
    version: 'Version',
    characterReference: '3.1 + Character',
    soundGeneration: 'Sound generation',
    videoWithSound: 'Video + sound',
    videoOnly: 'Video only',
    resolution: 'Resolution',
    length: 'Length',
    seed: 'Seed',
    seedPlaceholder: 'Enter seed',
    randomize: 'Randomize',
    negativePrompt: 'Negative prompt',
    negativePromptPlaceholder: 'What to avoid in the video...',
    // Auth pages
    welcomeBack: 'Welcome Back',
    loginToAccount: 'Login to your account to continue',
    email: 'Email',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    loggingIn: 'Logging in...',
    loginFailed: 'Login failed. Please try again.',
    dontHaveAccount: "Don't have an account?",
    backToHome: 'Back to Home',
    createAccount: 'Create Account',
    registerToGetStarted: 'Register to get started with AI tools',
    confirmPassword: 'Confirm Password',
    passwordMinLength: 'Minimum 6 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    registering: 'Registering...',
    registrationFailed: 'Registration failed. Please try again.',
    alreadyHaveAccount: 'Already have an account?',
    // Landing page
    heroTitle: 'Create Amazing Content with AI',
    heroSubtitle: 'Get access to powerful AI tools and create professional videos and images in seconds',
    startButton: 'Get Started',
    packagesTitle: 'PACKAGES',
    packagesSubtitle: 'All packages give access to the same AI tools. The difference is how much you use each model.',
    mostPopular: 'Most popular',
    perMonth: '/ month',
    credits: 'credits',
    suitableFor: 'Suitable for:',
    starterSuitable: 'beginners, small businesses',
    proSuitable: 'SMMs, content creators',
    agencySuitable: 'agencies, teams, heavy users',
    estimatedUsage: 'Estimated usage capabilities 👇',
    aiVideo: '🎥 AI Video:',
    aiImage: '🖼 AI Image:',
    standardVideo: '~{count} standard video',
    premiumVideo: 'or ~{count} premium video',
    images: '~{count} images',
    included: 'Included',
    starterNote: '👉 Ideal for getting started',
    proNote: '👉 Best choice for continuous use',
    agencyNote: '👉 Maximum power for teams and agencies',
    selectPlan: 'Select',
    importantNote: '🔍 IMPORTANT NOTE',
    importantNoteText: 'All packages give access to the same AI tools. The difference: how much you use each model. More realistic AI models use more credits, standard models use fewer credits. 👉 You decide which one to choose.',
    topupTitle: '➕ TOP-UP CREDIT',
    topupSubtitle: '🔋 Credits running out?',
    topupDescription: 'No need to stop. Buy as many additional credits as you want and continue.',
    loading: 'Loading...',
    topupSuitableSmall: 'Suitable for: unfinished work',
    topupSuitableMedium: 'Suitable for: finishing the month without problems',
    topupSuitableLarge: 'Suitable for: agencies and intensive use',
    topupSmallFeatures: '• 1–2 additional videos\n• or a few image / audio operations\n• Activates immediately',
    topupSmallNote: '👉 Continue quickly',
    topupMediumFeatures: '• Several AI videos\n• Balanced image + audio usage\n• No need to change package',
    topupMediumNote: '👉 Most economical choice',
    topupLargeFeatures: '• High volume work\n• Ideal for premium AI models\n• Can be used anytime',
    topupLargeNote: '👉 Maximum comfort',
    buyTopup: 'Buy',
    topupInfoTitle: 'ℹ️ EXPLANATORY NOTE',
    topupWhatIs: 'What is top-up credit?',
    topupWhatIsText: 'Top-up: additional credit to your existing package, does not change your package, unlimited (stays until used up).',
    topupDifference: 'What is the difference between package and top-up?',
    topupDifferenceText: 'Package: most economical credit value. Top-up: for comfort and continuous continuation.',
    topupTip: '📌 If you use more, upgrading your package next month may be more economical.',
    creditsHowTitle: 'How does the credit system work?',
    creditsStep1Title: '1. Package selection',
    creditsStep1Text: 'You buy a package → it contains credits. The user spends credits as they wish.',
    creditsStep2Title: '2. Credit usage',
    creditsStep2Text: 'Each AI model uses a certain number of credits. When a video job starts, credits are HELD, when the job completes successfully they are CONFIRMED, if it fails they are RELEASED (returned).',
    creditsStep3Title: '3. Top-up (additional credit)',
    creditsStep3Text: 'When credits run out, you can buy Top-up (additional credit). Top-up credits appear immediately in balance, are unlimited (stay until used up), do not change subscription.',
    creditsStep4Title: '4. Auto-renew (automatic renewal)',
    creditsStep4Text: 'The package automatically renews when the month ends and new monthly credits are added to the credit balance. Old remaining credits are reset (NO ROLLOVER).',
    // Dashboard page
    availableCredit: 'Available credit',
    heldCredits: 'Held',
    totalBalance: 'Total balance',
    creditsHeldProcessing: '{count} credits held in processing jobs',
    creditsLowTopup: 'Credits running low, top-up',
    topupContinue: 'Buy top-up and continue',
    // My Jobs page
    myJobs: 'My Jobs',
    myJobsDescription: 'List of AI videos and images you created',
    pleaseLogin: 'Please login',
    all: 'All',
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    creditsUsed: '{count} credits used',
    reason: 'Reason:',
    download: 'Download',
    noJobsFound: 'No jobs found',
    // Billing page
    billingSubscription: 'Billing & Subscription',
    billingDescription: 'Manage your subscription plan and view payment history',
    currentPlan: 'Current Plan',
    changePlan: 'Change Plan',
    plan: 'Plan',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    nextBillingDate: 'Next billing date',
    autoRenewal: 'Auto-renewal',
    noActiveSubscription: 'No active subscription',
    selectPackage: 'Select Package',
    topupCredit: 'Top-up Credit',
    buyTopup: 'Buy Top-up',
    topupDescription: 'When your credits run out, you can buy additional credits. Top-up credits are unlimited and do not change your package.',
    invoices: 'Invoices',
           noInvoices: 'No invoices',
           subscription: 'Subscription',
           searchModels: 'Search models...',
           noModelsFound: 'No models found',
  },
  az: {
    create: 'Yarat',
    dashboard: 'Panellər',
    templates: 'Şablonlar',
    credits: 'Kreditlər',
    upgrade: 'Yüksəlt',
    profile: 'Profil',
    settings: 'Parametrlər',
    logout: 'Çıxış',
    jobs: 'İşlərim',
    billing: 'Ödəniş',
    documents: 'Sənədlər',
    legalDocuments: 'Hüquqi sənədlər',
    privacyPolicy: 'Məxfilik siyasəti',
    termsOfUse: 'İstifadə şərtləri',
    cookiePolicy: 'Cookie siyasəti',
    refundPolicy: 'Geri qaytarma və ləğv siyasəti',
    packages: 'Paketlər',
    landing: 'Ana Səhifə',
    quickLinks: 'Tez keçidlər',
    language: 'Dil',
    english: 'İngilis dili',
    azerbaijani: 'Azərbaycan dili',
    russian: 'Rus dili',
    theme: 'Mövzu',
    notifications: 'Bildirişlər',
    account: 'Hesab',
    getStarted: 'Başla',
    browseTemplates: 'Şablonlara Bax',
    createAmazingContent: 'AI ilə Əla Məzmun Yaradın',
    accessPowerfulTools: 'Video, şəkil və audio yaradılması üçün güclü AI alətlərinə vahid platformada çıxış əldə edin',
    videoTools: 'Video Alətləri',
    imageTools: 'Şəkil Alətləri',
    audioTools: 'Audio Alətləri',
    generateVideos: 'AI ilə videoları yaradın, təkmilləşdirin və transformasiya edin',
    createImages: 'Mətn təkliflərindən gözəl şəkillər yaradın',
    generateAudio: 'AI ilə audio məzmunu yaradın və emal edin',
    aiToolsDashboard: 'AI Alətləri Paneli',
    accessTools: 'Video, şəkil və audio yaradılması üçün güclü AI alətlərinə çıxış',
    availableCredits: 'Mövcud Kreditlər',
    lowCredits: 'Az Kredit - Daha Çox Al',
    allTools: 'Bütün Alətlər',
    video: 'Video',
    image: 'Şəkil',
    audio: 'Audio',
    noToolsAvailable: 'Bu kateqoriyada alət yoxdur',
    selectLanguage: 'İstədiyiniz dili seçin',
    enableNotifications: 'Bildirişləri aktiv et',
    receiveSystemNotifications: 'Sistem bildirişləri alın',
    emailNotifications: 'Email bildirişləri',
    receiveEmailNotifications: 'Email vasitəsilə bildirişlər alın',
    darkMode: 'Qaranlıq rejim',
    darkTheme: 'Qaranlıq tema',
    lightMode: 'Açıq rejim',
    lightTheme: 'Açıq tema',
    changePassword: 'Şifrəni dəyişdir',
    changeEmail: 'Email adresini dəyişdir',
    payment: 'Ödəniş',
    managePaymentMethods: 'Ödəniş metodlarını idarə et',
    accountInvoice: 'Hesab fakturası',
    // Create page
    createPromptPlaceholder: 'Nə yaratmaq istəyirsiniz?',
    enterPrompt: 'Zəhmət olmasa prompt daxil edin',
    loginRequired: 'Zəhmət olmasa əvvəlcə daxil olun',
    selectTool: 'Zəhmət olmasa alət seçin',
    insufficientCredits: 'Kifayət qədər kredit yoxdur',
    videoGenerated: 'Video uğurla yaradıldı!',
    videoProcessing: 'Video emal olunur. Sonra yoxlayın!',
    videoGenerationFailed: 'Video yaradılması uğursuz oldu. Yenidən cəhd edin.',
    generatedVideo: 'Yaradılmış Video',
    generatingVideo: 'Video yaradılır... Bu bir neçə dəqiqə çəkə bilər.',
    controls: 'İdarəetmə',
    tools: 'Alətlər',
    projects: 'Proyektlər',
    firstProject: 'İlk proyekt',
    noCreationsYet: 'Hələ heç nə yaradılmayıb',
    incognito: 'Gizli',
    cost: 'Qiymət',
    version: 'Versiya',
    characterReference: '3.1 + Xarakter',
    soundGeneration: 'Səs yaradılması',
    videoWithSound: 'Video + səs',
    videoOnly: 'Yalnız video',
    resolution: 'Keyfiyyət',
    length: 'Müddət',
    seed: 'Seed',
    seedPlaceholder: 'Seed daxil edin',
    randomize: 'Təsadüfi',
    negativePrompt: 'Negativ prompt',
    negativePromptPlaceholder: 'Videoda nə olmamalıdır...',
    // Auth pages
    welcomeBack: 'Xoş gəlmisiniz',
    loginToAccount: 'Hesabınıza daxil olmaq üçün giriş edin',
    email: 'Email',
    enterEmail: 'Email daxil edin',
    password: 'Şifrə',
    enterPassword: 'Şifrənizi daxil edin',
    loggingIn: 'Giriş edilir...',
    loginFailed: 'Giriş uğursuz oldu. Yenidən cəhd edin.',
    dontHaveAccount: 'Hesabınız yoxdur?',
    backToHome: 'Ana Səhifəyə Qayıt',
    createAccount: 'Hesab Yaradın',
    registerToGetStarted: 'AI alətləri ilə başlamaq üçün qeydiyyatdan keçin',
    confirmPassword: 'Şifrəni Təsdiqləyin',
    passwordMinLength: 'Minimum 6 simvol',
    passwordsDoNotMatch: 'Şifrələr uyğun gəlmir',
    passwordTooShort: 'Şifrə ən azı 6 simvol olmalıdır',
    registering: 'Qeydiyyatdan keçilir...',
    registrationFailed: 'Qeydiyyat uğursuz oldu. Yenidən cəhd edin.',
    alreadyHaveAccount: 'Artıq hesabınız var?',
  },
  ru: {
    create: 'Создать',
    dashboard: 'Панель',
    templates: 'Шаблоны',
    credits: 'Кредиты',
    upgrade: 'Обновить',
    profile: 'Профиль',
    settings: 'Настройки',
    logout: 'Выход',
    jobs: 'Мои работы',
    billing: 'Оплата',
    documents: 'Документы',
    legalDocuments: 'Юридические документы',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfUse: 'Условия использования',
    cookiePolicy: 'Политика cookie',
    refundPolicy: 'Политика возврата и отмены',
    packages: 'Пакеты',
    landing: 'Главная',
    quickLinks: 'Быстрые ссылки',
    language: 'Язык',
    english: 'Английский',
    azerbaijani: 'Азербайджанский',
    russian: 'Русский',
    theme: 'Тема',
    notifications: 'Уведомления',
    account: 'Аккаунт',
    getStarted: 'Начать',
    browseTemplates: 'Просмотр Шаблонов',
    createAmazingContent: 'Создавайте Потрясающий Контент с ИИ',
    accessPowerfulTools: 'Получите доступ к мощным инструментам ИИ для создания видео, изображений и аудио на единой платформе',
    videoTools: 'Видео Инструменты',
    imageTools: 'Инструменты Изображений',
    audioTools: 'Аудио Инструменты',
    generateVideos: 'Создавайте, улучшайте и преобразуйте видео с помощью ИИ',
    createImages: 'Создавайте потрясающие изображения из текстовых подсказок',
    generateAudio: 'Создавайте и обрабатывайте аудиоконтент с помощью ИИ',
    aiToolsDashboard: 'Панель Инструментов ИИ',
    accessTools: 'Доступ к мощным инструментам ИИ для создания видео, изображений и аудио',
    availableCredits: 'Доступные Кредиты',
    lowCredits: 'Мало Кредитов - Купить Больше',
    allTools: 'Все Инструменты',
    video: 'Видео',
    image: 'Изображение',
    audio: 'Аудио',
    noToolsAvailable: 'Нет доступных инструментов в этой категории',
    selectLanguage: 'Выберите желаемый язык',
    enableNotifications: 'Включить уведомления',
    receiveSystemNotifications: 'Получать системные уведомления',
    emailNotifications: 'Уведомления по электронной почте',
    receiveEmailNotifications: 'Получать уведомления по электронной почте',
    darkMode: 'Темный режим',
    darkTheme: 'Темная тема',
    lightMode: 'Светлый режим',
    lightTheme: 'Светлая тема',
    changePassword: 'Изменить пароль',
    changeEmail: 'Изменить адрес электронной почты',
    payment: 'Платеж',
    managePaymentMethods: 'Управление способами оплаты',
    accountInvoice: 'Счет-фактура',
    // Create page
    createPromptPlaceholder: 'Что вы хотите создать?',
    enterPrompt: 'Пожалуйста, введите запрос',
    loginRequired: 'Пожалуйста, сначала войдите',
    selectTool: 'Пожалуйста, выберите инструмент',
    insufficientCredits: 'Недостаточно кредитов',
    videoGenerated: 'Видео успешно создано!',
    videoProcessing: 'Видео обрабатывается. Проверьте позже!',
    videoGenerationFailed: 'Не удалось создать видео. Попробуйте еще раз.',
    generatedVideo: 'Созданное Видео',
    generatingVideo: 'Создание видео... Это может занять несколько минут.',
    controls: 'Управление',
    tools: 'Инструменты',
    projects: 'Проекты',
    firstProject: 'Первый проект',
    noCreationsYet: 'Пока ничего не создано',
    incognito: 'Инкогнито',
    cost: 'Стоимость',
    version: 'Версия',
    characterReference: '3.1 + Персонаж',
    soundGeneration: 'Генерация звука',
    videoWithSound: 'Видео + звук',
    videoOnly: 'Только видео',
    resolution: 'Разрешение',
    length: 'Длина',
    seed: 'Seed',
    seedPlaceholder: 'Введите seed',
    randomize: 'Случайно',
    negativePrompt: 'Негативный промпт',
    negativePromptPlaceholder: 'Что не должно быть в видео...',
    // Auth pages
    welcomeBack: 'С возвращением',
    loginToAccount: 'Войдите в свой аккаунт, чтобы продолжить',
    email: 'Электронная почта',
    enterEmail: 'Введите ваш email',
    password: 'Пароль',
    enterPassword: 'Введите ваш пароль',
    loggingIn: 'Вход...',
    loginFailed: 'Вход не удался. Попробуйте еще раз.',
    dontHaveAccount: 'Нет аккаунта?',
    backToHome: 'Вернуться на главную',
    createAccount: 'Создать аккаунт',
    registerToGetStarted: 'Зарегистрируйтесь, чтобы начать работу с AI инструментами',
    confirmPassword: 'Подтвердите пароль',
    passwordMinLength: 'Минимум 6 символов',
    passwordsDoNotMatch: 'Пароли не совпадают',
    passwordTooShort: 'Пароль должен содержать минимум 6 символов',
    registering: 'Регистрация...',
    registrationFailed: 'Регистрация не удалась. Попробуйте еще раз.',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    // Landing page
    heroTitle: 'Создавайте Потрясающий Контент с ИИ',
    heroSubtitle: 'Получите доступ к мощным инструментам ИИ и создавайте профессиональные видео и изображения за секунды',
    startButton: 'Начать',
    packagesTitle: 'ПАКЕТЫ',
    packagesSubtitle: 'Все пакеты дают доступ к одним и тем же инструментам ИИ. Разница в том, сколько вы используете каждую модель.',
    mostPopular: 'Самый популярный',
    perMonth: '/ месяц',
    credits: 'кредитов',
    suitableFor: 'Подходит для:',
    starterSuitable: 'начинающих, малого бизнеса',
    proSuitable: 'SMM, создателей контента',
    agencySuitable: 'агентств, команд, активных пользователей',
    estimatedUsage: 'Примерные возможности использования 👇',
    aiVideo: '🎥 ИИ Видео:',
    aiImage: '🖼 ИИ Изображение:',
    standardVideo: '~{count} стандартных видео',
    premiumVideo: 'или ~{count} премиум видео',
    images: '~{count} изображений',
    included: 'Включено',
    starterNote: '👉 Идеально для начала',
    proNote: '👉 Лучший выбор для постоянного использования',
    agencyNote: '👉 Максимальная мощность для команд и агентств',
    selectPlan: 'Выбрать',
    importantNote: '🔍 ВАЖНОЕ ПРИМЕЧАНИЕ',
    importantNoteText: 'Все пакеты дают доступ к одним и тем же инструментам ИИ. Разница: сколько вы используете каждую модель. Более реалистичные модели ИИ используют больше кредитов, стандартные модели используют меньше кредитов. 👉 Вы решаете, что выбрать.',
    topupTitle: '➕ ДОПОЛНИТЕЛЬНЫЙ КРЕДИТ',
    topupSubtitle: '🔋 Кредиты заканчиваются?',
    topupDescription: 'Не нужно останавливаться. Купите столько дополнительных кредитов, сколько хотите, и продолжайте.',
    loading: 'Загрузка...',
    topupSuitableSmall: 'Подходит для: незавершенной работы',
    topupSuitableMedium: 'Подходит для: завершения месяца без проблем',
    topupSuitableLarge: 'Подходит для: агентств и интенсивного использования',
    topupSmallFeatures: '• 1–2 дополнительных видео\n• или несколько операций с изображением / аудио\n• Активируется немедленно',
    topupSmallNote: '👉 Продолжить быстро',
    topupMediumFeatures: '• Несколько видео ИИ\n• Сбалансированное использование изображений + аудио\n• Не нужно менять пакет',
    topupMediumNote: '👉 Самый экономичный выбор',
    topupLargeFeatures: '• Работа с большим объемом\n• Идеально для премиум моделей ИИ\n• Можно использовать в любое время',
    topupLargeNote: '👉 Максимальный комфорт',
    buyTopup: 'Купить',
    topupInfoTitle: 'ℹ️ ПОЯСНИТЕЛЬНАЯ ЗАМЕТКА',
    topupWhatIs: 'Что такое дополнительный кредит?',
    topupWhatIsText: 'Дополнительный кредит: дополнительный кредит к вашему существующему пакету, не меняет ваш пакет, без ограничений (остается до использования).',
    topupDifference: 'В чем разница между пакетом и дополнительным кредитом?',
    topupDifferenceText: 'Пакет: наиболее экономичная стоимость кредита. Дополнительный кредит: для удобства и непрерывного продолжения.',
    topupTip: '📌 Если вы используете больше, обновление пакета в следующем месяце может быть более экономичным.',
    creditsHowTitle: 'Как работает система кредитов?',
    creditsStep1Title: '1. Выбор пакета',
    creditsStep1Text: 'Вы покупаете пакет → он содержит кредиты. Пользователь тратит кредиты по своему желанию.',
    creditsStep2Title: '2. Использование кредитов',
    creditsStep2Text: 'Каждая модель ИИ использует определенное количество кредитов. Когда начинается видео-задача, кредиты УДЕРЖИВАЮТСЯ, когда задача успешно завершается, они ПОДТВЕРЖДАЮТСЯ, если она не удается, они ОСВОБОЖДАЮТСЯ (возвращаются).',
    creditsStep3Title: '3. Дополнительный кредит',
    creditsStep3Text: 'Когда кредиты заканчиваются, вы можете купить дополнительный кредит. Дополнительные кредиты сразу появляются в балансе, без ограничений (остаются до использования), не меняют подписку.',
    creditsStep4Title: '4. Автоматическое продление',
    creditsStep4Text: 'Пакет автоматически продлевается в конце месяца, и новые месячные кредиты добавляются к балансу кредитов. Старые оставшиеся кредиты сбрасываются (БЕЗ ПЕРЕНОСА).',
    // Dashboard page
    availableCredit: 'Доступный кредит',
    heldCredits: 'Заблокировано',
    totalBalance: 'Общий баланс',
    creditsHeldProcessing: '{count} кредитов заблокировано в обработке',
    creditsLowTopup: 'Кредиты заканчиваются, пополнить',
    topupContinue: 'Купить пополнение и продолжить',
    // My Jobs page
    myJobs: 'Мои работы',
    myJobsDescription: 'Список созданных вами видео и изображений ИИ',
    pleaseLogin: 'Пожалуйста, войдите',
    all: 'Все',
    pending: 'Ожидание',
    processing: 'Обработка',
    completed: 'Завершено',
    failed: 'Не удалось',
    creditsUsed: 'Использовано {count} кредитов',
    reason: 'Причина:',
    download: 'Скачать',
    noJobsFound: 'Работы не найдены',
    // Billing page
    billingSubscription: 'Оплата и подписка',
    billingDescription: 'Управляйте планом подписки и просматривайте историю платежей',
    currentPlan: 'Текущий план',
    changePlan: 'Изменить план',
    plan: 'План',
    status: 'Статус',
    active: 'Активен',
    inactive: 'Неактивен',
    nextBillingDate: 'Следующая дата оплаты',
    autoRenewal: 'Автоматическое продление',
    noActiveSubscription: 'Нет активной подписки',
    selectPackage: 'Выбрать пакет',
    topupCredit: 'Дополнительный кредит',
    buyTopup: 'Купить пополнение',
    topupDescription: 'Когда кредиты заканчиваются, вы можете купить дополнительные кредиты. Дополнительные кредиты без ограничений и не меняют ваш пакет.',
    invoices: 'Счета-фактуры',
    noInvoices: 'Нет счетов-фактур',
    subscription: 'Подписка',
    searchModels: 'Поиск моделей...',
    noModelsFound: 'Модели не найдены',
  },
}

// Load from localStorage on init
const getStoredLanguage = (): Language => {
  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      const stored = localStorage.getItem('language')
      if (stored && ['en', 'az', 'ru'].includes(stored)) {
        return stored as Language
      }
    }
  } catch (e) {
    console.error('Error loading language from localStorage:', e)
  }
  return 'en'
}

export const useLanguageStore = create<LanguageStore>((set) => ({
  language: getStoredLanguage(),
  setLanguage: (lang) => {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem('language', lang)
      }
    } catch (e) {
      console.error('Error saving language to localStorage:', e)
    }
    set({ language: lang })
  },
  translations,
}))

export const useTranslation = () => {
  const { language, translations } = useLanguageStore()
  return (key: string) => {
    try {
      return translations[language]?.[key] || translations['en']?.[key] || key
    } catch (e) {
      console.error('Translation error:', e)
      return key
    }
  }
}

