import { create } from 'zustand'

export type Language = 'en' | 'az' | 'ru'

interface LanguageStore {
  language: Language
  setLanguage: (lang: Language) => void
  translations: Record<Language, Record<string, string>>
}

const translations = {
  en: {
    create: 'Create',
    dashboard: 'Dashboard',
    templates: 'Templates',
    credits: 'Credits',
    upgrade: 'Upgrade',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    jobs: 'My Jobs',
    billing: 'Billing',
    documents: 'Documents',
    legalDocuments: 'Legal & documents',
    privacyPolicy: 'Privacy policy',
    termsOfUse: 'Terms of use',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie policy',
    refundPolicy: 'Refund & cancellation policy',
    packages: 'Packages',
    landing: 'Landing',
    quickLinks: 'Quick Links',
    footerDescription: 'AI-powered professional video and image creation platform. Bring your creative ideas to life with powerful AI models.',
    support: 'Support',
    contact: 'Contact',
    address: 'Baku, Azerbaijan',
    allRightsReserved: 'All rights reserved.',
    developedBy: 'Developed by',
    documentation: 'Documentation',
    about: 'About',
    aboutUs: 'About Us',
    aboutDescription: 'Burlart - AI-powered professional video and image creation platform. Bring your creative ideas to life with powerful AI models.',
    ourMission: 'Our Mission',
    missionText: 'Our mission is to provide everyone with the ability to create high-quality videos and images using AI technologies. Whether you are a professional designer or a beginner, you can easily bring your creative ideas to life with Burlart.',
    missionText2: 'We strive to provide the best experience to our users by combining the latest AI models in one platform.',
    fastGeneration: 'Fast Generation',
    fastGenerationText: 'Create high-quality content in seconds',
    highQuality: 'High Quality',
    highQualityText: 'Professional-level results',
    powerfulModels: 'Powerful Models',
    powerfulModelsText: 'Sora, Veo, Kling AI and other powerful models',
    team: 'Team',
    teamDescription: 'The Burlart team consists of experienced specialists in AI technologies and creative design.',
    teamText: 'Our team is committed to the development of AI technologies and providing the best experience to our users. Each member is an expert in their field and works to continuously improve our platform.',
    teamText2: 'Burlart is developed and maintained by Trivasoft.',
    technology: 'Technology',
    technologyDescription: 'Burlart uses the latest AI technologies',
    soraDescription: 'OpenAI\'s powerful video creation model',
    veoDescription: 'Google\'s latest video creation technology',
    klingDescription: 'High-quality video creation',
    fluxDescription: 'Professional-level image creation',
    pikaDescription: 'Fast and quality video creation',
    andMore: 'And More',
    andMoreText: 'Other powerful AI models',
    getInTouch: 'Get in Touch',
    getInTouchText: 'If you have questions or suggestions, please contact us.',
    contactUs: 'Contact Us',
    visitTrivasoft: 'Visit Trivasoft',
    careers: 'Careers',
    trivasoft: 'Trivasoft',
    language: 'Language',
    english: 'English',
    azerbaijani: 'Azerbaijani',
    russian: 'Russian',
    theme: 'Theme',
    notifications: 'Notifications',
    account: 'Account',
    getStarted: 'Get Started',
    browseTemplates: 'Browse Templates',
    createAmazingContent: 'Create Amazing Content with AI',
    accessPowerfulTools: 'Access powerful AI tools for video, image, and audio generation in one unified platform',
    videoTools: 'Video Tools',
    imageTools: 'Image Tools',
    audioTools: 'Audio Tools',
    generateVideos: 'Generate, enhance, and transform videos with AI',
    createImages: 'Create stunning images from text prompts',
    generateAudio: 'Generate and process audio content with AI',
    aiToolsDashboard: 'AI Tools Dashboard',
    accessTools: 'Access powerful AI tools for video, image, and audio generation',
    availableCredits: 'Available Credits',
    lowCredits: 'Low Credits - Buy More',
    allTools: 'All Tools',
    myTools: 'My',
    video: 'Video',
    image: 'Image',
    audio: 'Audio',
    noToolsAvailable: 'No tools available in this category',
    creditsExhausted: 'Your credits have run out. Buy top-up to continue using AI tools.',
    clearSearch: 'Clear search',
    closeSearch: 'Close search',
    noFavoriteToolsYet: 'No favorite or recently used tools yet',
    selectLanguage: 'Select your desired language',
    enableNotifications: 'Enable notifications',
    receiveSystemNotifications: 'Receive system notifications',
    emailNotifications: 'Email notifications',
    receiveEmailNotifications: 'Receive notifications via email',
    darkMode: 'Dark mode',
    darkTheme: 'Dark theme',
    lightMode: 'Light mode',
    lightTheme: 'Light theme',
    changePassword: 'Change password',
    changeEmail: 'Change email address',
    payment: 'Payment',
    managePaymentMethods: 'Manage payment methods',
    accountInvoice: 'Account invoice',
    // Create page
    createPromptPlaceholder: 'What do you want to create?',
    enterPrompt: 'Please enter a prompt',
    loginRequired: 'Please login first',
    selectTool: 'Please select a tool',
    insufficientCredits: 'Insufficient credits',
    videoGenerated: 'Video generated successfully!',
    videoProcessing: 'Video is being processed. Check back soon!',
    videoGenerationFailed: 'Video generation failed. Please try again.',
    generatedVideo: 'Generated Video',
    generatingVideo: 'Generating video... This may take a few moments.',
    controls: 'Controls',
    tools: 'Tools',
    projects: 'Projects',
    firstProject: 'First project',
    noCreationsYet: 'No creations yet',
    incognito: 'Incognito',
    cost: 'Cost',
    version: 'Version',
    characterReference: '3.1 + Character',
    soundGeneration: 'Sound generation',
    videoWithSound: 'Video + sound',
    videoOnly: 'Video only',
    resolution: 'Resolution',
    length: 'Length',
    seed: 'Seed',
    seedPlaceholder: 'Enter seed',
    randomize: 'Randomize',
    negativePrompt: 'Negative prompt',
    negativePromptPlaceholder: 'What to avoid in the video...',
    // Auth pages
    welcomeBack: 'Welcome Back',
    loginToAccount: 'Login to your account to continue',
    email: 'Email',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    loggingIn: 'Logging in...',
    loginFailed: 'Login failed. Please try again.',
    dontHaveAccount: "Don't have an account?",
    backToHome: 'Back to Home',
    createAccount: 'Create Account',
    registerToGetStarted: 'Register to get started with AI tools',
    confirmPassword: 'Confirm Password',
    passwordMinLength: 'Minimum 6 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    registering: 'Registering...',
    registrationFailed: 'Registration failed. Please try again.',
    alreadyHaveAccount: 'Already have an account?',
    // Landing page
    heroTitle: 'Create Amazing Content with AI',
    heroSubtitle: 'Get access to powerful AI tools and create professional videos and images in seconds',
    startButton: 'Get Started',
    packagesTitle: 'PACKAGES',
    packagesSubtitle: 'All packages give access to the same AI tools. The difference is how much you use each model.',
    mostPopular: 'Most popular',
    perMonth: '/ month',
    suitableFor: 'Suitable for:',
    starterSuitable: 'beginners, small businesses',
    proSuitable: 'SMMs, content creators',
    agencySuitable: 'agencies, teams, heavy users',
    estimatedUsage: 'Estimated usage capabilities 👇',
    aiVideo: '🎥 AI Video:',
    aiImage: '🖼 AI Image:',
    standardVideo: '~{count} standard video',
    premiumVideo: 'or ~{count} premium video',
    images: '~{count} images',
    included: 'Included',
    starterNote: '👉 Ideal for getting started',
    proNote: '👉 Best choice for continuous use',
    agencyNote: '👉 Maximum power for teams and agencies',
    selectPlan: 'Select',
    importantNote: '🔍 IMPORTANT NOTE',
    importantNoteText: 'All packages give access to the same AI tools. The difference: how much you use each model. More realistic AI models use more credits, standard models use fewer credits. 👉 You decide which one to choose.',
    topupTitle: '➕ TOP-UP KREDİT',
    topupSubtitle: '🔋 Kreditləriniz bitmək üzrədir?',
    topupDescription: 'Dayanmağa ehtiyac yoxdur. İstədiyiniz qədər əlavə kredit alıb davam edin.',
    loading: 'Yüklənir...',
    topupSuitableSmall: 'Uyğundur: yarımçıq işlər üçün',
    topupSuitableMedium: 'Uyğundur: ayı problemsiz başa vurmaq üçün',
    topupSuitableLarge: 'Uyğundur: agentliklər və intensiv istifadə üçün',
    topupSmallFeatures: '• 1–2 əlavə video\n• və ya bir neçə şəkil / audio əməliyyatı\n• Dərhal aktivləşir',
    topupSmallNote: '👉 Tez davam etmək üçün',
    topupMediumFeatures: '• Bir neçə AI video\n• Balanslı şəkil + audio istifadə\n• Paketi dəyişməyə ehtiyac yoxdur',
    topupMediumNote: '👉 Ən sərfəli seçim',
    topupLargeFeatures: '• Yüksək həcmli işlər\n• Premium AI modelləri üçün idealdır\n• İstənilən vaxt istifadə oluna bilər',
    topupLargeNote: '👉 Maksimum rahatlıq',
    buyTopup: 'Top-up al',
    topupRequiresSubscription: 'Top-up kredit yalnız aktiv abunəliyi olan istifadəçilər üçündür. Zəhmət olmasa əvvəlcə paket seçin.',
    topupInfoTitle: 'ℹ️ İZAHEDİCİ QEYD',
    topupWhatIs: 'Top-up kredit nədir?',
    topupWhatIsText: 'Top-up: mövcud paketinizə əlavə kreditdir, paketi dəyişmir, məhdudiyyətsizdir (bitənə kimi qalır).',
    topupDifference: 'Paket və top-up arasında fərq nədir?',
    topupDifferenceText: 'Paket: ən sərfəli kredit dəyəri. Top-up: komfort və fasiləsiz davam üçün əlavə rahatlıqdır.',
    topupTip: '📌 Əgər daha çox istifadə edirsinizsə, növbəti ay paketi yüksəltmək daha sərfəli ola bilər.',
    creditsHowTitle: 'How does the credit system work?',
    creditsStep1Title: '1. Package selection',
    creditsStep1Text: 'You buy a package → it contains credits. The user spends credits as they wish.',
    creditsStep2Title: '2. Credit usage',
    creditsStep2Text: 'Each AI model uses a certain number of credits. When a video job starts, credits are HELD, when the job completes successfully they are CONFIRMED, if it fails they are RELEASED (returned).',
    creditsStep3Title: '3. Top-up (additional credit)',
    creditsStep3Text: 'When credits run out, you can buy Top-up (additional credit). Top-up credits appear immediately in balance, are unlimited (stay until used up), do not change subscription.',
    creditsStep4Title: '4. Auto-renew (automatic renewal)',
    creditsStep4Text: 'The package automatically renews when the month ends and new monthly credits are added to the credit balance. Old remaining credits are reset (NO ROLLOVER).',
    // Dashboard page
    availableCredit: 'Available credit',
    heldCredits: 'Held',
    totalBalance: 'Total balance',
    creditsHeldProcessing: '{count} credits held in processing jobs',
    creditsLowTopup: 'Credits running low, top-up',
    topupContinue: 'Buy top-up and continue',
    // My Jobs page
    myJobs: 'My Jobs',
    myJobsDescription: 'List of AI videos and images you created',
    pleaseLogin: 'Please login',
    all: 'All',
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    creditsUsed: '{count} credits used',
    reason: 'Reason:',
    download: 'Download',
    noJobsFound: 'No jobs found',
    // Billing page
    billingSubscription: 'Billing & Subscription',
    billingDescription: 'Manage your subscription plan and view payment history',
    currentPlan: 'Current Plan',
    changePlan: 'Change Plan',
    plan: 'Plan',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    nextBillingDate: 'Next billing date',
    autoRenewal: 'Auto-renewal',
    noActiveSubscription: 'No active subscription',
    selectPackage: 'Select Package',
    topupCredit: 'Top-up Credit',
    invoices: 'Invoices',
           noInvoices: 'No invoices',
           subscription: 'Subscription',
           searchModels: 'Search models...',
           noModelsFound: 'No models found',
  },
  az: {
    create: 'Yarat',
    dashboard: 'Panellər',
    templates: 'Şablonlar',
    credits: 'Kreditlər',
    upgrade: 'Yüksəlt',
    profile: 'Profil',
    settings: 'Parametrlər',
    logout: 'Çıxış',
    jobs: 'İşlərim',
    billing: 'Ödəniş',
    documents: 'Sənədlər',
    legalDocuments: 'Hüquqi sənədlər',
    privacyPolicy: 'Məxfilik siyasəti',
    termsOfUse: 'İstifadə şərtləri',
    termsOfService: 'Xidmət Şərtləri',
    cookiePolicy: 'Cookie siyasəti',
    refundPolicy: 'Geri qaytarma və ləğv siyasəti',
    packages: 'Paketlər',
    landing: 'Ana Səhifə',
    quickLinks: 'Tez keçidlər',
    footerDescription: 'AI ilə peşəkar video və şəkil yaratma platforması. Güclü AI modelləri ilə kreativ ideyalarınızı həyata keçirin.',
    support: 'Dəstək',
    contact: 'Əlaqə',
    address: 'Bakı, Azərbaycan',
    allRightsReserved: 'Bütün hüquqlar qorunur.',
    developedBy: 'Tərəfindən hazırlanıb',
    documentation: 'Sənədlər',
    about: 'Haqqında',
    aboutUs: 'Haqqımızda',
    aboutDescription: 'Burlart - AI ilə peşəkar video və şəkil yaratma platforması. Güclü AI modelləri ilə kreativ ideyalarınızı həyata keçirin.',
    ourMission: 'Missiyamız',
    missionText: 'Bizim missiyamız hər kəsə AI texnologiyaları ilə yüksək keyfiyyətli video və şəkillər yaratmaq imkanı verməkdir. İstər peşəkar dizayner, istərsə də yeni başlayan olsun, Burlart ilə kreativ ideyalarınızı asanlıqla həyata keçirə bilərsiniz.',
    missionText2: 'Biz ən son AI modellərini bir platformada birləşdirərək, istifadəçilərimizə ən yaxşı təcrübəni təqdim etməyə çalışırıq.',
    fastGeneration: 'Sürətli Yaradılma',
    fastGenerationText: 'Saniyələr ərzində yüksək keyfiyyətli kontent yaradın',
    highQuality: 'Yüksək Keyfiyyət',
    highQualityText: 'Peşəkar səviyyədə nəticələr',
    powerfulModels: 'Güclü Modellər',
    powerfulModelsText: 'Sora, Veo, Kling AI və digər güclü modellər',
    team: 'Komanda',
    teamDescription: 'Burlart komandası AI texnologiyaları və kreativ dizayn sahəsində təcrübəli mütəxəssislərdən ibarətdir.',
    teamText: 'Bizim komandamız AI texnologiyalarının inkişafına və istifadəçilərimizə ən yaxşı təcrübəni təqdim etməyə sadiqdir. Hər bir üzvümüz öz sahəsində mütəxəssisdir və platformamızın daim təkmilləşdirilməsi üçün çalışır.',
    teamText2: 'Burlart, Trivasoft şirkəti tərəfindən hazırlanmış və inkişaf etdirilmişdir.',
    technology: 'Texnologiya',
    technologyDescription: 'Burlart ən son AI texnologiyalarından istifadə edir',
    soraDescription: 'OpenAI-nin güclü video yaratma modeli',
    veoDescription: 'Google-ın ən son video yaratma texnologiyası',
    klingDescription: 'Yüksək keyfiyyətli video yaratma',
    fluxDescription: 'Peşəkar səviyyədə şəkil yaratma',
    pikaDescription: 'Sürətli və keyfiyyətli video yaratma',
    andMore: 'Və Daha Çox',
    andMoreText: 'Digər güclü AI modelləri',
    getInTouch: 'Əlaqə Saxlayın',
    getInTouchText: 'Suallarınız və ya təklifləriniz varsa, bizimlə əlaqə saxlayın.',
    contactUs: 'Bizimlə Əlaqə',
    visitTrivasoft: 'Trivasoft-u Ziyarət Et',
    careers: 'Karyera',
    trivasoft: 'Trivasoft',
    language: 'Dil',
    english: 'İngilis dili',
    azerbaijani: 'Azərbaycan dili',
    russian: 'Rus dili',
    theme: 'Mövzu',
    notifications: 'Bildirişlər',
    account: 'Hesab',
    getStarted: 'Başla',
    browseTemplates: 'Şablonlara Bax',
    createAmazingContent: 'AI ilə Əla Məzmun Yaradın',
    accessPowerfulTools: 'Video, şəkil və audio yaradılması üçün güclü AI alətlərinə vahid platformada çıxış əldə edin',
    videoTools: 'Video Alətləri',
    imageTools: 'Şəkil Alətləri',
    audioTools: 'Audio Alətləri',
    generateVideos: 'AI ilə videoları yaradın, təkmilləşdirin və transformasiya edin',
    createImages: 'Mətn təkliflərindən gözəl şəkillər yaradın',
    generateAudio: 'AI ilə audio məzmunu yaradın və emal edin',
    aiToolsDashboard: 'AI Alətləri Paneli',
    accessTools: 'Video, şəkil və audio yaradılması üçün güclü AI alətlərinə çıxış',
    availableCredits: 'Mövcud Kreditlər',
    availableCredit: 'Mövcud kredit',
    heldCredits: 'Bloklanmış',
    totalBalance: 'Ümumi balans',
    lowCredits: 'Az Kredit - Daha Çox Al',
    allTools: 'Bütün Alətlər',
    myTools: 'Mənim',
    video: 'Video',
    image: 'Şəkil',
    audio: 'Audio',
    noToolsAvailable: 'Bu kateqoriyada alət yoxdur',
    creditsExhausted: 'Kreditləriniz bitib. Top-up alın ki, AI alətlərindən istifadə edə biləsiniz.',
    clearSearch: 'Axtarışı təmizlə',
    closeSearch: 'Axtarışı bağla',
    noFavoriteToolsYet: 'Hələ sevimli və ya yaxınlarda istifadə olunan alət yoxdur',
    selectLanguage: 'İstədiyiniz dili seçin',
    enableNotifications: 'Bildirişləri aktiv et',
    receiveSystemNotifications: 'Sistem bildirişləri alın',
    emailNotifications: 'Email bildirişləri',
    receiveEmailNotifications: 'Email vasitəsilə bildirişlər alın',
    darkMode: 'Qaranlıq rejim',
    darkTheme: 'Qaranlıq tema',
    lightMode: 'Açıq rejim',
    lightTheme: 'Açıq tema',
    changePassword: 'Şifrəni dəyişdir',
    changeEmail: 'Email adresini dəyişdir',
    payment: 'Ödəniş',
    managePaymentMethods: 'Ödəniş metodlarını idarə et',
    accountInvoice: 'Hesab fakturası',
    // Create page
    createPromptPlaceholder: 'Nə yaratmaq istəyirsiniz?',
    enterPrompt: 'Zəhmət olmasa prompt daxil edin',
    loginRequired: 'Zəhmət olmasa əvvəlcə daxil olun',
    selectTool: 'Zəhmət olmasa alət seçin',
    insufficientCredits: 'Kifayət qədər kredit yoxdur',
    videoGenerated: 'Video uğurla yaradıldı!',
    videoProcessing: 'Video emal olunur. Sonra yoxlayın!',
    videoGenerationFailed: 'Video yaradılması uğursuz oldu. Yenidən cəhd edin.',
    generatedVideo: 'Yaradılmış Video',
    generatingVideo: 'Video yaradılır... Bu bir neçə dəqiqə çəkə bilər.',
    controls: 'İdarəetmə',
    tools: 'Alətlər',
    projects: 'Proyektlər',
    firstProject: 'İlk proyekt',
    noCreationsYet: 'Hələ heç nə yaradılmayıb',
    incognito: 'Gizli',
    cost: 'Qiymət',
    version: 'Versiya',
    characterReference: '3.1 + Xarakter',
    soundGeneration: 'Səs yaradılması',
    videoWithSound: 'Video + səs',
    videoOnly: 'Yalnız video',
    resolution: 'Keyfiyyət',
    length: 'Müddət',
    seed: 'Seed',
    seedPlaceholder: 'Seed daxil edin',
    randomize: 'Təsadüfi',
    negativePrompt: 'Negativ prompt',
    negativePromptPlaceholder: 'Videoda nə olmamalıdır...',
    // Auth pages
    welcomeBack: 'Xoş gəlmisiniz',
    loginToAccount: 'Hesabınıza daxil olmaq üçün giriş edin',
    email: 'Email',
    enterEmail: 'Email daxil edin',
    password: 'Şifrə',
    enterPassword: 'Şifrənizi daxil edin',
    loggingIn: 'Giriş edilir...',
    loginFailed: 'Giriş uğursuz oldu. Yenidən cəhd edin.',
    dontHaveAccount: 'Hesabınız yoxdur?',
    backToHome: 'Ana Səhifəyə Qayıt',
    createAccount: 'Hesab Yaradın',
    registerToGetStarted: 'AI alətləri ilə başlamaq üçün qeydiyyatdan keçin',
    confirmPassword: 'Şifrəni Təsdiqləyin',
    passwordMinLength: 'Minimum 6 simvol',
    passwordsDoNotMatch: 'Şifrələr uyğun gəlmir',
    passwordTooShort: 'Şifrə ən azı 6 simvol olmalıdır',
    registering: 'Qeydiyyatdan keçilir...',
    registrationFailed: 'Qeydiyyat uğursuz oldu. Yenidən cəhd edin.',
    alreadyHaveAccount: 'Artıq hesabınız var?',
  },
  ru: {
    create: 'Создать',
    dashboard: 'Панель',
    templates: 'Шаблоны',
    credits: 'Кредиты',
    upgrade: 'Обновить',
    profile: 'Профиль',
    settings: 'Настройки',
    logout: 'Выход',
    jobs: 'Мои работы',
    billing: 'Оплата',
    documents: 'Документы',
    legalDocuments: 'Юридические документы',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfUse: 'Условия использования',
    termsOfService: 'Условия обслуживания',
    cookiePolicy: 'Политика cookie',
    refundPolicy: 'Политика возврата и отмены',
    packages: 'Пакеты',
    landing: 'Главная',
    quickLinks: 'Быстрые ссылки',
    footerDescription: 'Платформа для создания профессиональных видео и изображений с помощью ИИ. Воплощайте свои творческие идеи с помощью мощных моделей ИИ.',
    support: 'Поддержка',
    contact: 'Контакты',
    address: 'Баку, Азербайджан',
    allRightsReserved: 'Все права защищены.',
    developedBy: 'Разработано',
    documentation: 'Документация',
    about: 'О нас',
    aboutUs: 'О нас',
    aboutDescription: 'Burlart - платформа для создания профессиональных видео и изображений с помощью ИИ. Воплощайте свои творческие идеи с помощью мощных моделей ИИ.',
    ourMission: 'Наша миссия',
    missionText: 'Наша миссия - предоставить каждому возможность создавать высококачественные видео и изображения с помощью технологий ИИ. Будь вы профессиональным дизайнером или новичком, вы можете легко воплотить свои творческие идеи с Burlart.',
    missionText2: 'Мы стремимся предоставить нашим пользователям лучший опыт, объединяя последние модели ИИ на одной платформе.',
    fastGeneration: 'Быстрое создание',
    fastGenerationText: 'Создавайте высококачественный контент за секунды',
    highQuality: 'Высокое качество',
    highQualityText: 'Результаты профессионального уровня',
    powerfulModels: 'Мощные модели',
    powerfulModelsText: 'Sora, Veo, Kling AI и другие мощные модели',
    team: 'Команда',
    teamDescription: 'Команда Burlart состоит из опытных специалистов в области технологий ИИ и творческого дизайна.',
    teamText: 'Наша команда привержена развитию технологий ИИ и предоставлению лучшего опыта нашим пользователям. Каждый член является экспертом в своей области и работает над постоянным улучшением нашей платформы.',
    teamText2: 'Burlart разработан и поддерживается компанией Trivasoft.',
    technology: 'Технология',
    technologyDescription: 'Burlart использует новейшие технологии ИИ',
    soraDescription: 'Мощная модель создания видео от OpenAI',
    veoDescription: 'Новейшая технология создания видео от Google',
    klingDescription: 'Создание высококачественного видео',
    fluxDescription: 'Создание изображений профессионального уровня',
    pikaDescription: 'Быстрое и качественное создание видео',
    andMore: 'И многое другое',
    andMoreText: 'Другие мощные модели ИИ',
    getInTouch: 'Свяжитесь с нами',
    getInTouchText: 'Если у вас есть вопросы или предложения, пожалуйста, свяжитесь с нами.',
    contactUs: 'Связаться с нами',
    visitTrivasoft: 'Посетить Trivasoft',
    careers: 'Карьера',
    trivasoft: 'Trivasoft',
    language: 'Язык',
    english: 'Английский',
    azerbaijani: 'Азербайджанский',
    russian: 'Русский',
    theme: 'Тема',
    notifications: 'Уведомления',
    account: 'Аккаунт',
    getStarted: 'Начать',
    browseTemplates: 'Просмотр Шаблонов',
    createAmazingContent: 'Создавайте Потрясающий Контент с ИИ',
    accessPowerfulTools: 'Получите доступ к мощным инструментам ИИ для создания видео, изображений и аудио на единой платформе',
    videoTools: 'Видео Инструменты',
    imageTools: 'Инструменты Изображений',
    audioTools: 'Аудио Инструменты',
    generateVideos: 'Создавайте, улучшайте и преобразуйте видео с помощью ИИ',
    createImages: 'Создавайте потрясающие изображения из текстовых подсказок',
    generateAudio: 'Создавайте и обрабатывайте аудиоконтент с помощью ИИ',
    aiToolsDashboard: 'Панель Инструментов ИИ',
    accessTools: 'Доступ к мощным инструментам ИИ для создания видео, изображений и аудио',
    availableCredits: 'Доступные Кредиты',
    lowCredits: 'Мало Кредитов - Купить Больше',
    allTools: 'Все Инструменты',
    myTools: 'Мои',
    video: 'Видео',
    image: 'Изображение',
    audio: 'Аудио',
    noToolsAvailable: 'Нет доступных инструментов в этой категории',
    creditsExhausted: 'Ваши кредиты закончились. Купите топ-ап, чтобы продолжить использовать инструменты ИИ.',
    clearSearch: 'Очистить поиск',
    closeSearch: 'Закрыть поиск',
    noFavoriteToolsYet: 'Пока нет избранных или недавно использованных инструментов',
    selectLanguage: 'Выберите желаемый язык',
    enableNotifications: 'Включить уведомления',
    receiveSystemNotifications: 'Получать системные уведомления',
    emailNotifications: 'Уведомления по электронной почте',
    receiveEmailNotifications: 'Получать уведомления по электронной почте',
    darkMode: 'Темный режим',
    darkTheme: 'Темная тема',
    lightMode: 'Светлый режим',
    lightTheme: 'Светлая тема',
    changePassword: 'Изменить пароль',
    changeEmail: 'Изменить адрес электронной почты',
    payment: 'Платеж',
    managePaymentMethods: 'Управление способами оплаты',
    accountInvoice: 'Счет-фактура',
    // Create page
    createPromptPlaceholder: 'Что вы хотите создать?',
    enterPrompt: 'Пожалуйста, введите запрос',
    loginRequired: 'Пожалуйста, сначала войдите',
    selectTool: 'Пожалуйста, выберите инструмент',
    insufficientCredits: 'Недостаточно кредитов',
    videoGenerated: 'Видео успешно создано!',
    videoProcessing: 'Видео обрабатывается. Проверьте позже!',
    videoGenerationFailed: 'Не удалось создать видео. Попробуйте еще раз.',
    generatedVideo: 'Созданное Видео',
    generatingVideo: 'Создание видео... Это может занять несколько минут.',
    controls: 'Управление',
    tools: 'Инструменты',
    projects: 'Проекты',
    firstProject: 'Первый проект',
    noCreationsYet: 'Пока ничего не создано',
    incognito: 'Инкогнито',
    cost: 'Стоимость',
    version: 'Версия',
    characterReference: '3.1 + Персонаж',
    soundGeneration: 'Генерация звука',
    videoWithSound: 'Видео + звук',
    videoOnly: 'Только видео',
    resolution: 'Разрешение',
    length: 'Длина',
    seed: 'Seed',
    seedPlaceholder: 'Введите seed',
    randomize: 'Случайно',
    negativePrompt: 'Негативный промпт',
    negativePromptPlaceholder: 'Что не должно быть в видео...',
    // Auth pages
    welcomeBack: 'С возвращением',
    loginToAccount: 'Войдите в свой аккаунт, чтобы продолжить',
    email: 'Электронная почта',
    enterEmail: 'Введите ваш email',
    password: 'Пароль',
    enterPassword: 'Введите ваш пароль',
    loggingIn: 'Вход...',
    loginFailed: 'Вход не удался. Попробуйте еще раз.',
    dontHaveAccount: 'Нет аккаунта?',
    backToHome: 'Вернуться на главную',
    createAccount: 'Создать аккаунт',
    registerToGetStarted: 'Зарегистрируйтесь, чтобы начать работу с AI инструментами',
    confirmPassword: 'Подтвердите пароль',
    passwordMinLength: 'Минимум 6 символов',
    passwordsDoNotMatch: 'Пароли не совпадают',
    passwordTooShort: 'Пароль должен содержать минимум 6 символов',
    registering: 'Регистрация...',
    registrationFailed: 'Регистрация не удалась. Попробуйте еще раз.',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    // Landing page
    heroTitle: 'Создавайте Потрясающий Контент с ИИ',
    heroSubtitle: 'Получите доступ к мощным инструментам ИИ и создавайте профессиональные видео и изображения за секунды',
    startButton: 'Начать',
    packagesTitle: 'ПАКЕТЫ',
    packagesSubtitle: 'Все пакеты дают доступ к одним и тем же инструментам ИИ. Разница в том, сколько вы используете каждую модель.',
    mostPopular: 'Самый популярный',
    perMonth: '/ месяц',
    suitableFor: 'Подходит для:',
    starterSuitable: 'начинающих, малого бизнеса',
    proSuitable: 'SMM, создателей контента',
    agencySuitable: 'агентств, команд, активных пользователей',
    estimatedUsage: 'Примерные возможности использования 👇',
    aiVideo: '🎥 ИИ Видео:',
    aiImage: '🖼 ИИ Изображение:',
    standardVideo: '~{count} стандартных видео',
    premiumVideo: 'или ~{count} премиум видео',
    images: '~{count} изображений',
    included: 'Включено',
    starterNote: '👉 Идеально для начала',
    proNote: '👉 Лучший выбор для постоянного использования',
    agencyNote: '👉 Максимальная мощность для команд и агентств',
    selectPlan: 'Выбрать',
    importantNote: '🔍 ВАЖНОЕ ПРИМЕЧАНИЕ',
    importantNoteText: 'Все пакеты дают доступ к одним и тем же инструментам ИИ. Разница: сколько вы используете каждую модель. Более реалистичные модели ИИ используют больше кредитов, стандартные модели используют меньше кредитов. 👉 Вы решаете, что выбрать.',
    topupTitle: '➕ ДОПОЛНИТЕЛЬНЫЙ КРЕДИТ',
    topupSubtitle: '🔋 Кредиты заканчиваются?',
    topupDescription: 'Не нужно останавливаться. Купите столько дополнительных кредитов, сколько хотите, и продолжайте.',
    loading: 'Загрузка...',
    topupSuitableSmall: 'Подходит для: незавершенной работы',
    topupSuitableMedium: 'Подходит для: завершения месяца без проблем',
    topupSuitableLarge: 'Подходит для: агентств и интенсивного использования',
    topupSmallFeatures: '• 1–2 дополнительных видео\n• или несколько операций с изображением / аудио\n• Активируется немедленно',
    topupSmallNote: '👉 Продолжить быстро',
    topupMediumFeatures: '• Несколько видео ИИ\n• Сбалансированное использование изображений + аудио\n• Не нужно менять пакет',
    topupMediumNote: '👉 Самый экономичный выбор',
    topupLargeFeatures: '• Работа с большим объемом\n• Идеально для премиум моделей ИИ\n• Можно использовать в любое время',
    topupLargeNote: '👉 Максимальный комфорт',
    buyTopup: 'Купить',
    topupInfoTitle: 'ℹ️ ПОЯСНИТЕЛЬНАЯ ЗАМЕТКА',
    topupWhatIs: 'Что такое дополнительный кредит?',
    topupWhatIsText: 'Дополнительный кредит: дополнительный кредит к вашему существующему пакету, не меняет ваш пакет, без ограничений (остается до использования).',
    topupDifference: 'В чем разница между пакетом и дополнительным кредитом?',
    topupDifferenceText: 'Пакет: наиболее экономичная стоимость кредита. Дополнительный кредит: для удобства и непрерывного продолжения.',
    topupTip: '📌 Если вы используете больше, обновление пакета в следующем месяце может быть более экономичным.',
    creditsHowTitle: 'Как работает система кредитов?',
    creditsStep1Title: '1. Выбор пакета',
    creditsStep1Text: 'Вы покупаете пакет → он содержит кредиты. Пользователь тратит кредиты по своему желанию.',
    creditsStep2Title: '2. Использование кредитов',
    creditsStep2Text: 'Каждая модель ИИ использует определенное количество кредитов. Когда начинается видео-задача, кредиты УДЕРЖИВАЮТСЯ, когда задача успешно завершается, они ПОДТВЕРЖДАЮТСЯ, если она не удается, они ОСВОБОЖДАЮТСЯ (возвращаются).',
    creditsStep3Title: '3. Дополнительный кредит',
    creditsStep3Text: 'Когда кредиты заканчиваются, вы можете купить дополнительный кредит. Дополнительные кредиты сразу появляются в балансе, без ограничений (остаются до использования), не меняют подписку.',
    creditsStep4Title: '4. Автоматическое продление',
    creditsStep4Text: 'Пакет автоматически продлевается в конце месяца, и новые месячные кредиты добавляются к балансу кредитов. Старые оставшиеся кредиты сбрасываются (БЕЗ ПЕРЕНОСА).',
    // Dashboard page
    availableCredit: 'Доступный кредит',
    heldCredits: 'Заблокировано',
    totalBalance: 'Общий баланс',
    creditsHeldProcessing: '{count} кредитов заблокировано в обработке',
    creditsLowTopup: 'Кредиты заканчиваются, пополнить',
    topupContinue: 'Купить пополнение и продолжить',
    // My Jobs page
    myJobs: 'Мои работы',
    myJobsDescription: 'Список созданных вами видео и изображений ИИ',
    pleaseLogin: 'Пожалуйста, войдите',
    all: 'Все',
    pending: 'Ожидание',
    processing: 'Обработка',
    completed: 'Завершено',
    failed: 'Не удалось',
    creditsUsed: 'Использовано {count} кредитов',
    reason: 'Причина:',
    download: 'Скачать',
    noJobsFound: 'Работы не найдены',
    // Billing page
    billingSubscription: 'Оплата и подписка',
    billingDescription: 'Управляйте планом подписки и просматривайте историю платежей',
    currentPlan: 'Текущий план',
    changePlan: 'Изменить план',
    plan: 'План',
    status: 'Статус',
    active: 'Активен',
    inactive: 'Неактивен',
    nextBillingDate: 'Следующая дата оплаты',
    autoRenewal: 'Автоматическое продление',
    noActiveSubscription: 'Нет активной подписки',
    selectPackage: 'Выбрать пакет',
    topupCredit: 'Дополнительный кредит',
    invoices: 'Счета-фактуры',
    noInvoices: 'Нет счетов-фактур',
    subscription: 'Подписка',
    searchModels: 'Поиск моделей...',
    noModelsFound: 'Модели не найдены',
  },
}

// Load from localStorage on init
const getStoredLanguage = (): Language => {
  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      const stored = localStorage.getItem('language')
      if (stored && ['en', 'az', 'ru'].includes(stored)) {
        return stored as Language
      }
    }
  } catch (e) {
    console.error('Error loading language from localStorage:', e)
  }
  return 'en'
}

export const useLanguageStore = create<LanguageStore>((set) => ({
  language: getStoredLanguage(),
  setLanguage: (lang) => {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem('language', lang)
      }
    } catch (e) {
      console.error('Error saving language to localStorage:', e)
    }
    set({ language: lang })
  },
  translations,
}))

export const useTranslation = () => {
  const { language, translations } = useLanguageStore()
  return (key: string) => {
    try {
      return translations[language]?.[key] || translations['en']?.[key] || key
    } catch (e) {
      console.error('Translation error:', e)
      return key
    }
  }
}

